require("option-config")
require("keymap-config")
require("lazy-config")
require("mason-config")
require('autocommand-config')
require('lualine-config')
require('which-key-config')
require('treesitter-config')
require('telescope-config')
require('nvim-cmp-config')

require('neodev').setup()
